# theme
ID_THEME_SWITCH = "id-theme-switch"
ID_APP_THEME = "id-app-theme"
ID_LOADER = "id-loader"
ID_ALERT_DANGER = "id-alert_danger"
ID_ALERT_WARNING= "id-alert_warning"
ID_ALERT_INFO = "id-alert_info"
ID_LOGO_CONTAINER = "id-logo-container"

# UI elements
ID_APP_CONTAINER = "id-app-container"
ID_SETTINGS_DRAWER = "id-settings-drawer"
ID_MAP_LAYER_BOTTOM_DRAWER = "id-map-layer-bottom-drawer"
ID_OPEN_SETTINGS_DRAWER_BUTTON = "id-settings-drawer-btn"
ID_BOTTOM_DRAWER_BUTTON = "id-bottom-drawer-btn"
ID_MAP_SELECTOR_BUTTON = "id-map-selector-btn"
ID_MAP_SELECTION_POPUP = "id-map-selector-popup"
ID_MAP = "id-map"
ID_URL_LOCATION = 'id-url-location'
ID_SEARCH_DEPLOYMENT_BUTTON = "id-search-deployment-button"
ID_SEARCHBAR_SEARCH_DEPLOYMENT_BUTTON = "id-searchbar-search-deployment-button"
ID_DEPLOYMENT_SELECT = "id-deployment-select"
ID_DEPLOYMENT_SELECT_SEARCH_BAR = "id-deployment-select-search-bar"
ID_LOGOUT_BUTTON = "id-logout-btn"
ID_FAB_CONTAINER= "id-fab-container"
ID_LOGIN_AVATAR_CONTAINER = "id-login-avatar-container"
ID_ADD_NOTE_BUTTON = "id-add-note-button"
ID_DATA_DRAWER_TITLE = "id-data-drawer-title"
ID_STAY_LOGGED_IN_INTERVAL = "id-stay-logged-in-interval"
ID_LOGIN_BUTTON_HREF = "id_login_button_href"

# stores
ID_TAG_DATA_STORE = "id-tags-data-store"
ID_DEPLOYMENT_DATA_STORE = "id-deployment-data-store"
ID_SELECTED_MARKER_STORE = "id-selected-marker-store"
ID_BASE_MAP_STORE = {"role": "map_store", "type": "base"}
ID_OVERLAY_MAP_STORE = {"role": "map_store", "type": "overlay"}
ID_DATE_RANGE_STORE = "id-date-range-store"
ID_PREVENT_MARKER_EVENT = "id-prevent-marker-event"
ID_EDIT_NOTE_STORE = "id-edit-note-store"
ID_BROWSER_PROPERTIES_STORE = "id-browser-properties-store"
ID_NOTE_REFRESH_STORE = "id-note-refresh-store"
ID_BLOB_URLS_STORE = "id-blob-urls-store"
ID_NOTE_FILE_STORE = "id-note-file-store"
ID_QUERY_PARAM_STORE = "id-query-param-store"

# node types
ID_ALL_ACTIVE_STORE = "id-active-all-checkbox"
ID_TYPE_CHECKBOX_GROUP = "id-type-checkbox-group"

# date_time
ID_DATE_RANGE_PICKER = "id-date-range-picker"
ID_DATE_RANGE_SEGMENT = "id-time-range-segment"

# tags
ID_TAG_CHIPS_GROUP = "id-tag-chips-group"
ID_FS_TAG_CHIPS_GROUP = "id-fs-tag-chips-group"
ID_CHIPS_MODAL = "id-chip-modal"
ID_MODAL_CHIPS_GROUP = "id-modal-chips-group"
ID_CLOSE_CHIP_MODAL_BUTTON = "id-close-modal-btn"
ID_OPEN_CHIP_MODAL_BUTTON = "id-open-modal-btn"
ID_TAG_RESET_BUTTON = "id-tag-reset-button"

# left drawer
ID_LEFT_DRAWER_CONTENT_SCROLL_AREA = "id-scroll-div-container"
ID_CHART_CONTAINER = "id-chart-container"
ID_CHART_DRAWER = "id-chart-drawer"
ID_ENVIRONMENT_CHECKBOX = "id-environment-checkbox"

# map selection & handling
ID_MAP_LAYER_GROUP = "id-map-data-layer"
ID_ENV_LAYER_GROUP = "id-env-data-layer"
ID_HIGHLIGHT_LAYER_GROUP = "id-highlight-data-layer"
ID_NOTES_LAYER_GROUP = "id-notes-data-layer"
ID_BASE_LAYER_MAP = "id-map-tile-layer"
ID_OVERLAY_MAP = "id-map-overlay"
ID_MINIMAP_LABEL = "id-minimap-label"
ID_MINIMAP_LAYER_BUTTON = "id-minimap-layer-button"
ID_FOCUS_ON_MAP_LOCATION = "id-focus-on-map-position"
ID_MAP_IN_PROGRES = "id-map-in-progres"

# notes
ID_NOTE_ATTACHMENT_MODAL = "id-note-attachment-modal"
ID_NOTE_OPEN_MODAL_BUTTON = "id-note-open-modal-button"
ID_NOTE_EDIT_BUTTON = "id-note-edit-button"
ID_NOTE_ATTACHMENT_BUTTON = "id-note-attachment-button"
ID_NOTE_DELETE_BUTTON = "id-note-delete-button"
ID_NOTE_SAVE_EDIT_BUTTON = "id-note-save-edit-button"
ID_NOTE_EDIT_TITLE = "id-note-edit-title"
ID_NOTE_EDIT_DESCRIPTION = "id-note-edit-description"
ID_NOTE_VIEW = "id-note-view"
ID_NOTE_FORM_CANCEL_BUTTON = "id-note-form-cancel"
ID_NOTE_FORM_SAVE_BUTTON = "id-note-form-save"
ID_NOTE_DRAWER_TITLE = "id-note-drawer-title"
ID_NOTE_EDIT_LAT = "id-note-edit-lat"
ID_NOTE_EDIT_LON = "id-note-edit-lon"
ID_NOTE_EDIT_PUBLIC_FLAG = "id-note-edit-public-flag"
ID_CONFIRM_UNSAVED_CHANGES_DIALOG = "id-confirm-unsaved-changes-dialog"
ID_CONFIRM_DELETE_DIALOG = "id-confirm-delete-dialog"
ID_NOTE_TAG_SELECT = "id-note-tag-select"
ID_CREATE_NEW_TAG_BUTTON = "id-create-new-tag-button"
ID_NEW_TAG_INPUT = "id-new-tag-input"
ID_ATTACHMENTS = "id-attachment"
ID_ATTACHMENT_MODAL_FORM_BUTTON = "id-attachment-modal-form-button"
ID_ATTACHMENT_DELETE_BUTTON = "id-attachment-delete-button"
ID_SAVE_LOCATION_BUTTON = "id-save-location-button"
ID_EDIT_LOCATION_MODAL = "id-edit-location-modal"
ID_LOCATION_MODAL_BUTTON = "id-location-modal-button"
ID_IMAGE_UPLOAD = "id-upload-image"
ID_IMAGE_VIEW_MODAL = "id-image-view-modal"
ID_IMAGE_CAROUSEL = "id-image-carousel"
ID_DOWNLOAD = "id-download"
ID_NOTE_DATE_INPUT = "id-note-date-input"
ID_NOTE_TIME_INPUT = "id-note-time-input"
ID_SLIDESHOW_IMAGE = "id-slideshow-image"
ID_SLIDESHOW_BTN_LEFT = "id-slideshow-btn-left"
ID_SLIDESHOW_BTN_RIGHT = "id-slideshow-btn-right"
ID_NOTE_CONTAINER = "id-note-container"
ID_AUDIO = "id-audio"
ID_AUDIO_PLAYER = "id-audio-player"
