name: Docker Build and Publish

on:
  [workflow_dispatch]
  # push:
  #   branches: [ "main" ]
  #   tags: [ '*.*' ]

env:
  REGISTRY: cr.gitlab.fhnw.ch
  # github.repository as <account>/<repo>
  IMAGE_NAME: mitwelten/docker-infrastructure/mitwelten-discover_app

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Variables
        run: |
          echo "ref_name: ${{ github.ref_name }}"
          echo "ref_name: $GITHUB_REF_NAME"
          echo "ref: ${{ github.ref }}"

      # - name: Log into registry ${{ env.REGISTRY }}
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ secrets.ACTOR }}
      #     password: ${{ secrets.GITLAB_TOKEN }}

      # - name: Docker Build 
      #   run: |
      #     docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .
      # - name: Docker Push
      #   run: |
      #     docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

